name: BradHolly
favicon: null
layout_spectrum: 0.6038309999275953
typography_spectrum: 0.51505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#5876ac'
    - '#f4f0ed'
    - '#819cc5'
    - '#2c2b31'
  brandStrength: 0.5
  lightness: 0.33327379496768117
  saturation: 0.0016589947044849396
  rhythmicContrast: 0.9271125860977918
purpose: []
